
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORDIVIDIDOASIGNAR CALCULAR_IMPUESTO DIVIDIDO ENTONCES ID IGUAL MAS MAYOR MENOR MENOS NUMERO PAR_DER PAR_IZQ POR PUNTO_Y_COMA SIprograma : lista_instruccioneslista_instrucciones : instruccionlista_instrucciones : lista_instrucciones instruccioninstruccion : asignacion\n                   | estructura_condicional\n                   | llamada_funcionasignacion : ID ASIGNAR expresion PUNTO_Y_COMAestructura_condicional : SI condicion ENTONCES instruccionllamada_funcion : CALCULAR_IMPUESTO PAR_IZQ expresion PAR_DER PUNTO_Y_COMAcondicion : expresion MAYOR expresion\n                 | expresion MENOR expresion\n                 | expresion IGUAL expresionexpresion : expresion MAS expresion\n                 | expresion MENOS expresion\n                 | expresion POR expresion\n                 | expresion DIVIDIDO expresionexpresion : PAR_IZQ expresion PAR_DERexpresion : NUMEROexpresion : ID'
    
_lr_action_items = {'ID':([0,2,3,4,5,6,8,10,11,14,17,19,20,21,22,23,24,25,26,29,30,40,],[7,7,-2,-4,-5,-6,16,-3,16,16,16,7,16,16,16,16,16,16,16,-7,-8,-9,]),'SI':([0,2,3,4,5,6,10,19,29,30,40,],[8,8,-2,-4,-5,-6,-3,8,-7,-8,-9,]),'CALCULAR_IMPUESTO':([0,2,3,4,5,6,10,19,29,30,40,],[9,9,-2,-4,-5,-6,-3,9,-7,-8,-9,]),'$end':([1,2,3,4,5,6,10,29,30,40,],[0,-1,-2,-4,-5,-6,-3,-7,-8,-9,]),'ASIGNAR':([7,],[11,]),'PAR_IZQ':([8,9,11,14,17,20,21,22,23,24,25,26,],[14,17,14,14,14,14,14,14,14,14,14,14,]),'NUMERO':([8,11,14,17,20,21,22,23,24,25,26,],[15,15,15,15,15,15,15,15,15,15,15,]),'ENTONCES':([12,15,16,31,32,33,34,35,36,37,38,],[19,-18,-19,-10,-11,-12,-13,-14,-15,-16,-17,]),'MAYOR':([13,15,16,34,35,36,37,38,],[20,-18,-19,-13,-14,-15,-16,-17,]),'MENOR':([13,15,16,34,35,36,37,38,],[21,-18,-19,-13,-14,-15,-16,-17,]),'IGUAL':([13,15,16,34,35,36,37,38,],[22,-18,-19,-13,-14,-15,-16,-17,]),'MAS':([13,15,16,18,27,28,31,32,33,34,35,36,37,38,],[23,-18,-19,23,23,23,23,23,23,-13,-14,-15,-16,-17,]),'MENOS':([13,15,16,18,27,28,31,32,33,34,35,36,37,38,],[24,-18,-19,24,24,24,24,24,24,-13,-14,-15,-16,-17,]),'POR':([13,15,16,18,27,28,31,32,33,34,35,36,37,38,],[25,-18,-19,25,25,25,25,25,25,25,25,-15,-16,-17,]),'DIVIDIDO':([13,15,16,18,27,28,31,32,33,34,35,36,37,38,],[26,-18,-19,26,26,26,26,26,26,26,26,-15,-16,-17,]),'PUNTO_Y_COMA':([15,16,18,34,35,36,37,38,39,],[-18,-19,29,-13,-14,-15,-16,-17,40,]),'PAR_DER':([15,16,27,28,34,35,36,37,38,],[-18,-19,38,39,-13,-14,-15,-16,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_instrucciones':([0,],[2,]),'instruccion':([0,2,19,],[3,10,30,]),'asignacion':([0,2,19,],[4,4,4,]),'estructura_condicional':([0,2,19,],[5,5,5,]),'llamada_funcion':([0,2,19,],[6,6,6,]),'condicion':([8,],[12,]),'expresion':([8,11,14,17,20,21,22,23,24,25,26,],[13,18,27,28,31,32,33,34,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_instrucciones','programa',1,'p_programa','parser.py',15),
  ('lista_instrucciones -> instruccion','lista_instrucciones',1,'p_lista_instrucciones_unica','parser.py',20),
  ('lista_instrucciones -> lista_instrucciones instruccion','lista_instrucciones',2,'p_lista_instrucciones_multiples','parser.py',24),
  ('instruccion -> asignacion','instruccion',1,'p_instruccion','parser.py',29),
  ('instruccion -> estructura_condicional','instruccion',1,'p_instruccion','parser.py',30),
  ('instruccion -> llamada_funcion','instruccion',1,'p_instruccion','parser.py',31),
  ('asignacion -> ID ASIGNAR expresion PUNTO_Y_COMA','asignacion',4,'p_asignacion','parser.py',36),
  ('estructura_condicional -> SI condicion ENTONCES instruccion','estructura_condicional',4,'p_estructura_condicional','parser.py',41),
  ('llamada_funcion -> CALCULAR_IMPUESTO PAR_IZQ expresion PAR_DER PUNTO_Y_COMA','llamada_funcion',5,'p_llamada_funcion','parser.py',46),
  ('condicion -> expresion MAYOR expresion','condicion',3,'p_condicion','parser.py',51),
  ('condicion -> expresion MENOR expresion','condicion',3,'p_condicion','parser.py',52),
  ('condicion -> expresion IGUAL expresion','condicion',3,'p_condicion','parser.py',53),
  ('expresion -> expresion MAS expresion','expresion',3,'p_expresion_binaria','parser.py',63),
  ('expresion -> expresion MENOS expresion','expresion',3,'p_expresion_binaria','parser.py',64),
  ('expresion -> expresion POR expresion','expresion',3,'p_expresion_binaria','parser.py',65),
  ('expresion -> expresion DIVIDIDO expresion','expresion',3,'p_expresion_binaria','parser.py',66),
  ('expresion -> PAR_IZQ expresion PAR_DER','expresion',3,'p_expresion_agrupada','parser.py',71),
  ('expresion -> NUMERO','expresion',1,'p_expresion_numero','parser.py',76),
  ('expresion -> ID','expresion',1,'p_expresion_id','parser.py',81),
]
